name: Buildpack build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pack-install:
    strategy:
      matrix:
        languages:
          - java
          - python
    runs-on: ubuntu-latest
    steps:
      - name: Install Pack Cli
        shell: bash
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli

      # build-docker-image:
      #   runs-on: ubuntu-latest
      #   needs:
      #     - pack-install
      #   steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        shell: bash
        working-directory: ${{ matrix.languages }}
        run: |
          pack build --builder gcr.io/buildpacks/builder ${{ matrix-languages }}-function
