name: Buildpack build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pack-install:
    strategy:
      matrix:
        languages:
          - java
          - python
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Install Pack Cli
        shell: bash
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli

      - name: checkout
        uses: actions/checkout@v6

      - name: build
        shell: bash
        working-directory: ${{ matrix.languages }}
        run: |
          pack build --builder gcr.io/buildpacks/builder ${{ matrix.languages }}-function

      - name: tag
        shell: bash
        run: |
          docker tag ${{ matrix.languages }}-function ghcr.io/gat786/buildpack-samples-${{ matrix.languages }}-function

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push
        shell: bash
        run: |
          docker push ghcr.io/gat786/buildpack-samples-${{ matrix.languages }}-function
